/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiBootstrapOrgRouteImport } from './routes/api/bootstrap-org'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as appAuthedRouteRouteImport } from './routes/(app)/_authed/route'
import { Route as ApiHolidaysIndexRouteImport } from './routes/api/holidays/index'
import { Route as ApiSummaryMonthlyRouteImport } from './routes/api/summary/monthly'
import { Route as ApiSummaryMineRouteImport } from './routes/api/summary/mine'
import { Route as ApiSummaryLockRouteImport } from './routes/api/summary/lock'
import { Route as ApiSummaryCsvRouteImport } from './routes/api/summary/csv'
import { Route as ApiOrganizationUpdateRouteImport } from './routes/api/organization/update'
import { Route as ApiOrganizationRemoveMemberRouteImport } from './routes/api/organization/remove-member'
import { Route as ApiOrganizationMembersRouteImport } from './routes/api/organization/members'
import { Route as ApiOrganizationInvitationsRouteImport } from './routes/api/organization/invitations'
import { Route as ApiOrganizationChangeRoleRouteImport } from './routes/api/organization/change-role'
import { Route as ApiOrganizationAcceptInvitationRouteImport } from './routes/api/organization/accept-invitation'
import { Route as ApiLeaveRequestsRejectRouteImport } from './routes/api/leave-requests/reject'
import { Route as ApiLeaveRequestsListOrgRouteImport } from './routes/api/leave-requests/list-org'
import { Route as ApiLeaveRequestsListMineRouteImport } from './routes/api/leave-requests/list-mine'
import { Route as ApiLeaveRequestsCreateRouteImport } from './routes/api/leave-requests/create'
import { Route as ApiLeaveRequestsCancelRouteImport } from './routes/api/leave-requests/cancel'
import { Route as ApiLeaveRequestsApproveRouteImport } from './routes/api/leave-requests/approve'
import { Route as ApiHolidaysDeleteRouteImport } from './routes/api/holidays/delete'
import { Route as ApiHolidaysCreateRouteImport } from './routes/api/holidays/create'
import { Route as ApiCorrectionRequestsRejectRouteImport } from './routes/api/correction-requests/reject'
import { Route as ApiCorrectionRequestsListOrgRouteImport } from './routes/api/correction-requests/list-org'
import { Route as ApiCorrectionRequestsListMineRouteImport } from './routes/api/correction-requests/list-mine'
import { Route as ApiCorrectionRequestsCreateRouteImport } from './routes/api/correction-requests/create'
import { Route as ApiCorrectionRequestsCancelRouteImport } from './routes/api/correction-requests/cancel'
import { Route as ApiCorrectionRequestsApproveRouteImport } from './routes/api/correction-requests/approve'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAttendanceTodayRouteImport } from './routes/api/attendance/today'
import { Route as ApiAttendanceRemindersRouteImport } from './routes/api/attendance/reminders'
import { Route as ApiAttendanceListRouteImport } from './routes/api/attendance/list'
import { Route as ApiAttendanceEditEntryRouteImport } from './routes/api/attendance/edit-entry'
import { Route as ApiAttendanceDetailRouteImport } from './routes/api/attendance/detail'
import { Route as ApiAttendanceClockOutRouteImport } from './routes/api/attendance/clock-out'
import { Route as ApiAttendanceClockInRouteImport } from './routes/api/attendance/clock-in'
import { Route as ApiAttendanceBreakStartRouteImport } from './routes/api/attendance/break-start'
import { Route as ApiAttendanceBreakEndRouteImport } from './routes/api/attendance/break-end'
import { Route as ApiAttendanceAuditsRouteImport } from './routes/api/attendance/audits'
import { Route as publicInviteTokenRouteImport } from './routes/(public)/invite.$token'
import { Route as appAuthedProfileRouteImport } from './routes/(app)/_authed/profile'
import { Route as appAuthedDashboardRouteImport } from './routes/(app)/_authed/dashboard'
import { Route as appAuthedAdminRouteRouteImport } from './routes/(app)/_authed/admin/route'
import { Route as appAuthedRequestsIndexRouteImport } from './routes/(app)/_authed/requests/index'
import { Route as appAuthedLeavesIndexRouteImport } from './routes/(app)/_authed/leaves/index'
import { Route as appAuthedAttendanceIndexRouteImport } from './routes/(app)/_authed/attendance/index'
import { Route as appAuthedRequestsNewRouteImport } from './routes/(app)/_authed/requests/new'
import { Route as appAuthedLeavesNewRouteImport } from './routes/(app)/_authed/leaves/new'
import { Route as appAuthedAttendanceDateRouteImport } from './routes/(app)/_authed/attendance/$date'
import { Route as appAuthedAdminSummaryRouteImport } from './routes/(app)/_authed/admin/summary'
import { Route as appAuthedAdminRequestsRouteImport } from './routes/(app)/_authed/admin/requests'
import { Route as appAuthedAdminLeavesRouteImport } from './routes/(app)/_authed/admin/leaves'
import { Route as appAuthedAdminSettingsRouteRouteImport } from './routes/(app)/_authed/admin/settings/route'
import { Route as appAuthedAdminSettingsIndexRouteImport } from './routes/(app)/_authed/admin/settings/index'
import { Route as appAuthedAdminMembersIndexRouteImport } from './routes/(app)/_authed/admin/members/index'
import { Route as appAuthedAdminSettingsMembersRouteImport } from './routes/(app)/_authed/admin/settings/members'
import { Route as appAuthedAdminSettingsHolidaysRouteImport } from './routes/(app)/_authed/admin/settings/holidays'
import { Route as appAuthedAdminMembersUserIdIndexRouteImport } from './routes/(app)/_authed/admin/members/$userId/index'
import { Route as appAuthedAdminMembersUserIdDateRouteImport } from './routes/(app)/_authed/admin/members/$userId/$date'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapOrgRoute = ApiBootstrapOrgRouteImport.update({
  id: '/api/bootstrap-org',
  path: '/api/bootstrap-org',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedRouteRoute = appAuthedRouteRouteImport.update({
  id: '/(app)/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolidaysIndexRoute = ApiHolidaysIndexRouteImport.update({
  id: '/api/holidays/',
  path: '/api/holidays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryMonthlyRoute = ApiSummaryMonthlyRouteImport.update({
  id: '/api/summary/monthly',
  path: '/api/summary/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryMineRoute = ApiSummaryMineRouteImport.update({
  id: '/api/summary/mine',
  path: '/api/summary/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryLockRoute = ApiSummaryLockRouteImport.update({
  id: '/api/summary/lock',
  path: '/api/summary/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryCsvRoute = ApiSummaryCsvRouteImport.update({
  id: '/api/summary/csv',
  path: '/api/summary/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationUpdateRoute = ApiOrganizationUpdateRouteImport.update({
  id: '/api/organization/update',
  path: '/api/organization/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationRemoveMemberRoute =
  ApiOrganizationRemoveMemberRouteImport.update({
    id: '/api/organization/remove-member',
    path: '/api/organization/remove-member',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationMembersRoute = ApiOrganizationMembersRouteImport.update({
  id: '/api/organization/members',
  path: '/api/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationInvitationsRoute =
  ApiOrganizationInvitationsRouteImport.update({
    id: '/api/organization/invitations',
    path: '/api/organization/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationChangeRoleRoute =
  ApiOrganizationChangeRoleRouteImport.update({
    id: '/api/organization/change-role',
    path: '/api/organization/change-role',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationAcceptInvitationRoute =
  ApiOrganizationAcceptInvitationRouteImport.update({
    id: '/api/organization/accept-invitation',
    path: '/api/organization/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeaveRequestsRejectRoute = ApiLeaveRequestsRejectRouteImport.update({
  id: '/api/leave-requests/reject',
  path: '/api/leave-requests/reject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveRequestsListOrgRoute = ApiLeaveRequestsListOrgRouteImport.update({
  id: '/api/leave-requests/list-org',
  path: '/api/leave-requests/list-org',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveRequestsListMineRoute =
  ApiLeaveRequestsListMineRouteImport.update({
    id: '/api/leave-requests/list-mine',
    path: '/api/leave-requests/list-mine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeaveRequestsCreateRoute = ApiLeaveRequestsCreateRouteImport.update({
  id: '/api/leave-requests/create',
  path: '/api/leave-requests/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveRequestsCancelRoute = ApiLeaveRequestsCancelRouteImport.update({
  id: '/api/leave-requests/cancel',
  path: '/api/leave-requests/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveRequestsApproveRoute = ApiLeaveRequestsApproveRouteImport.update({
  id: '/api/leave-requests/approve',
  path: '/api/leave-requests/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolidaysDeleteRoute = ApiHolidaysDeleteRouteImport.update({
  id: '/api/holidays/delete',
  path: '/api/holidays/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolidaysCreateRoute = ApiHolidaysCreateRouteImport.update({
  id: '/api/holidays/create',
  path: '/api/holidays/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrectionRequestsRejectRoute =
  ApiCorrectionRequestsRejectRouteImport.update({
    id: '/api/correction-requests/reject',
    path: '/api/correction-requests/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorrectionRequestsListOrgRoute =
  ApiCorrectionRequestsListOrgRouteImport.update({
    id: '/api/correction-requests/list-org',
    path: '/api/correction-requests/list-org',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorrectionRequestsListMineRoute =
  ApiCorrectionRequestsListMineRouteImport.update({
    id: '/api/correction-requests/list-mine',
    path: '/api/correction-requests/list-mine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorrectionRequestsCreateRoute =
  ApiCorrectionRequestsCreateRouteImport.update({
    id: '/api/correction-requests/create',
    path: '/api/correction-requests/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorrectionRequestsCancelRoute =
  ApiCorrectionRequestsCancelRouteImport.update({
    id: '/api/correction-requests/cancel',
    path: '/api/correction-requests/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorrectionRequestsApproveRoute =
  ApiCorrectionRequestsApproveRouteImport.update({
    id: '/api/correction-requests/approve',
    path: '/api/correction-requests/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceTodayRoute = ApiAttendanceTodayRouteImport.update({
  id: '/api/attendance/today',
  path: '/api/attendance/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceRemindersRoute = ApiAttendanceRemindersRouteImport.update({
  id: '/api/attendance/reminders',
  path: '/api/attendance/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceListRoute = ApiAttendanceListRouteImport.update({
  id: '/api/attendance/list',
  path: '/api/attendance/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceEditEntryRoute = ApiAttendanceEditEntryRouteImport.update({
  id: '/api/attendance/edit-entry',
  path: '/api/attendance/edit-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceDetailRoute = ApiAttendanceDetailRouteImport.update({
  id: '/api/attendance/detail',
  path: '/api/attendance/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceClockOutRoute = ApiAttendanceClockOutRouteImport.update({
  id: '/api/attendance/clock-out',
  path: '/api/attendance/clock-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceClockInRoute = ApiAttendanceClockInRouteImport.update({
  id: '/api/attendance/clock-in',
  path: '/api/attendance/clock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceBreakStartRoute = ApiAttendanceBreakStartRouteImport.update({
  id: '/api/attendance/break-start',
  path: '/api/attendance/break-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceBreakEndRoute = ApiAttendanceBreakEndRouteImport.update({
  id: '/api/attendance/break-end',
  path: '/api/attendance/break-end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceAuditsRoute = ApiAttendanceAuditsRouteImport.update({
  id: '/api/attendance/audits',
  path: '/api/attendance/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const publicInviteTokenRoute = publicInviteTokenRouteImport.update({
  id: '/(public)/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedProfileRoute = appAuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedDashboardRoute = appAuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedAdminRouteRoute = appAuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedRequestsIndexRoute = appAuthedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedLeavesIndexRoute = appAuthedLeavesIndexRouteImport.update({
  id: '/leaves/',
  path: '/leaves/',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedAttendanceIndexRoute =
  appAuthedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => appAuthedRouteRoute,
  } as any)
const appAuthedRequestsNewRoute = appAuthedRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedLeavesNewRoute = appAuthedLeavesNewRouteImport.update({
  id: '/leaves/new',
  path: '/leaves/new',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedAttendanceDateRoute = appAuthedAttendanceDateRouteImport.update({
  id: '/attendance/$date',
  path: '/attendance/$date',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedAdminSummaryRoute = appAuthedAdminSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => appAuthedAdminRouteRoute,
} as any)
const appAuthedAdminRequestsRoute = appAuthedAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => appAuthedAdminRouteRoute,
} as any)
const appAuthedAdminLeavesRoute = appAuthedAdminLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => appAuthedAdminRouteRoute,
} as any)
const appAuthedAdminSettingsRouteRoute =
  appAuthedAdminSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appAuthedAdminRouteRoute,
  } as any)
const appAuthedAdminSettingsIndexRoute =
  appAuthedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appAuthedAdminSettingsRouteRoute,
  } as any)
const appAuthedAdminMembersIndexRoute =
  appAuthedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => appAuthedAdminRouteRoute,
  } as any)
const appAuthedAdminSettingsMembersRoute =
  appAuthedAdminSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => appAuthedAdminSettingsRouteRoute,
  } as any)
const appAuthedAdminSettingsHolidaysRoute =
  appAuthedAdminSettingsHolidaysRouteImport.update({
    id: '/holidays',
    path: '/holidays',
    getParentRoute: () => appAuthedAdminSettingsRouteRoute,
  } as any)
const appAuthedAdminMembersUserIdIndexRoute =
  appAuthedAdminMembersUserIdIndexRouteImport.update({
    id: '/members/$userId/',
    path: '/members/$userId/',
    getParentRoute: () => appAuthedAdminRouteRoute,
  } as any)
const appAuthedAdminMembersUserIdDateRoute =
  appAuthedAdminMembersUserIdDateRouteImport.update({
    id: '/members/$userId/$date',
    path: '/members/$userId/$date',
    getParentRoute: () => appAuthedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/api/bootstrap-org': typeof ApiBootstrapOrgRoute
  '/api/me': typeof ApiMeRoute
  '/': typeof publicIndexRoute
  '/admin': typeof appAuthedAdminRouteRouteWithChildren
  '/dashboard': typeof appAuthedDashboardRoute
  '/profile': typeof appAuthedProfileRoute
  '/invite/$token': typeof publicInviteTokenRoute
  '/api/attendance/audits': typeof ApiAttendanceAuditsRoute
  '/api/attendance/break-end': typeof ApiAttendanceBreakEndRoute
  '/api/attendance/break-start': typeof ApiAttendanceBreakStartRoute
  '/api/attendance/clock-in': typeof ApiAttendanceClockInRoute
  '/api/attendance/clock-out': typeof ApiAttendanceClockOutRoute
  '/api/attendance/detail': typeof ApiAttendanceDetailRoute
  '/api/attendance/edit-entry': typeof ApiAttendanceEditEntryRoute
  '/api/attendance/list': typeof ApiAttendanceListRoute
  '/api/attendance/reminders': typeof ApiAttendanceRemindersRoute
  '/api/attendance/today': typeof ApiAttendanceTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/correction-requests/approve': typeof ApiCorrectionRequestsApproveRoute
  '/api/correction-requests/cancel': typeof ApiCorrectionRequestsCancelRoute
  '/api/correction-requests/create': typeof ApiCorrectionRequestsCreateRoute
  '/api/correction-requests/list-mine': typeof ApiCorrectionRequestsListMineRoute
  '/api/correction-requests/list-org': typeof ApiCorrectionRequestsListOrgRoute
  '/api/correction-requests/reject': typeof ApiCorrectionRequestsRejectRoute
  '/api/holidays/create': typeof ApiHolidaysCreateRoute
  '/api/holidays/delete': typeof ApiHolidaysDeleteRoute
  '/api/leave-requests/approve': typeof ApiLeaveRequestsApproveRoute
  '/api/leave-requests/cancel': typeof ApiLeaveRequestsCancelRoute
  '/api/leave-requests/create': typeof ApiLeaveRequestsCreateRoute
  '/api/leave-requests/list-mine': typeof ApiLeaveRequestsListMineRoute
  '/api/leave-requests/list-org': typeof ApiLeaveRequestsListOrgRoute
  '/api/leave-requests/reject': typeof ApiLeaveRequestsRejectRoute
  '/api/organization/accept-invitation': typeof ApiOrganizationAcceptInvitationRoute
  '/api/organization/change-role': typeof ApiOrganizationChangeRoleRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/members': typeof ApiOrganizationMembersRoute
  '/api/organization/remove-member': typeof ApiOrganizationRemoveMemberRoute
  '/api/organization/update': typeof ApiOrganizationUpdateRoute
  '/api/summary/csv': typeof ApiSummaryCsvRoute
  '/api/summary/lock': typeof ApiSummaryLockRoute
  '/api/summary/mine': typeof ApiSummaryMineRoute
  '/api/summary/monthly': typeof ApiSummaryMonthlyRoute
  '/api/holidays/': typeof ApiHolidaysIndexRoute
  '/admin/settings': typeof appAuthedAdminSettingsRouteRouteWithChildren
  '/admin/leaves': typeof appAuthedAdminLeavesRoute
  '/admin/requests': typeof appAuthedAdminRequestsRoute
  '/admin/summary': typeof appAuthedAdminSummaryRoute
  '/attendance/$date': typeof appAuthedAttendanceDateRoute
  '/leaves/new': typeof appAuthedLeavesNewRoute
  '/requests/new': typeof appAuthedRequestsNewRoute
  '/attendance/': typeof appAuthedAttendanceIndexRoute
  '/leaves/': typeof appAuthedLeavesIndexRoute
  '/requests/': typeof appAuthedRequestsIndexRoute
  '/admin/settings/holidays': typeof appAuthedAdminSettingsHolidaysRoute
  '/admin/settings/members': typeof appAuthedAdminSettingsMembersRoute
  '/admin/members/': typeof appAuthedAdminMembersIndexRoute
  '/admin/settings/': typeof appAuthedAdminSettingsIndexRoute
  '/admin/members/$userId/$date': typeof appAuthedAdminMembersUserIdDateRoute
  '/admin/members/$userId/': typeof appAuthedAdminMembersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/api/bootstrap-org': typeof ApiBootstrapOrgRoute
  '/api/me': typeof ApiMeRoute
  '/': typeof publicIndexRoute
  '/admin': typeof appAuthedAdminRouteRouteWithChildren
  '/dashboard': typeof appAuthedDashboardRoute
  '/profile': typeof appAuthedProfileRoute
  '/invite/$token': typeof publicInviteTokenRoute
  '/api/attendance/audits': typeof ApiAttendanceAuditsRoute
  '/api/attendance/break-end': typeof ApiAttendanceBreakEndRoute
  '/api/attendance/break-start': typeof ApiAttendanceBreakStartRoute
  '/api/attendance/clock-in': typeof ApiAttendanceClockInRoute
  '/api/attendance/clock-out': typeof ApiAttendanceClockOutRoute
  '/api/attendance/detail': typeof ApiAttendanceDetailRoute
  '/api/attendance/edit-entry': typeof ApiAttendanceEditEntryRoute
  '/api/attendance/list': typeof ApiAttendanceListRoute
  '/api/attendance/reminders': typeof ApiAttendanceRemindersRoute
  '/api/attendance/today': typeof ApiAttendanceTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/correction-requests/approve': typeof ApiCorrectionRequestsApproveRoute
  '/api/correction-requests/cancel': typeof ApiCorrectionRequestsCancelRoute
  '/api/correction-requests/create': typeof ApiCorrectionRequestsCreateRoute
  '/api/correction-requests/list-mine': typeof ApiCorrectionRequestsListMineRoute
  '/api/correction-requests/list-org': typeof ApiCorrectionRequestsListOrgRoute
  '/api/correction-requests/reject': typeof ApiCorrectionRequestsRejectRoute
  '/api/holidays/create': typeof ApiHolidaysCreateRoute
  '/api/holidays/delete': typeof ApiHolidaysDeleteRoute
  '/api/leave-requests/approve': typeof ApiLeaveRequestsApproveRoute
  '/api/leave-requests/cancel': typeof ApiLeaveRequestsCancelRoute
  '/api/leave-requests/create': typeof ApiLeaveRequestsCreateRoute
  '/api/leave-requests/list-mine': typeof ApiLeaveRequestsListMineRoute
  '/api/leave-requests/list-org': typeof ApiLeaveRequestsListOrgRoute
  '/api/leave-requests/reject': typeof ApiLeaveRequestsRejectRoute
  '/api/organization/accept-invitation': typeof ApiOrganizationAcceptInvitationRoute
  '/api/organization/change-role': typeof ApiOrganizationChangeRoleRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/members': typeof ApiOrganizationMembersRoute
  '/api/organization/remove-member': typeof ApiOrganizationRemoveMemberRoute
  '/api/organization/update': typeof ApiOrganizationUpdateRoute
  '/api/summary/csv': typeof ApiSummaryCsvRoute
  '/api/summary/lock': typeof ApiSummaryLockRoute
  '/api/summary/mine': typeof ApiSummaryMineRoute
  '/api/summary/monthly': typeof ApiSummaryMonthlyRoute
  '/api/holidays': typeof ApiHolidaysIndexRoute
  '/admin/leaves': typeof appAuthedAdminLeavesRoute
  '/admin/requests': typeof appAuthedAdminRequestsRoute
  '/admin/summary': typeof appAuthedAdminSummaryRoute
  '/attendance/$date': typeof appAuthedAttendanceDateRoute
  '/leaves/new': typeof appAuthedLeavesNewRoute
  '/requests/new': typeof appAuthedRequestsNewRoute
  '/attendance': typeof appAuthedAttendanceIndexRoute
  '/leaves': typeof appAuthedLeavesIndexRoute
  '/requests': typeof appAuthedRequestsIndexRoute
  '/admin/settings/holidays': typeof appAuthedAdminSettingsHolidaysRoute
  '/admin/settings/members': typeof appAuthedAdminSettingsMembersRoute
  '/admin/members': typeof appAuthedAdminMembersIndexRoute
  '/admin/settings': typeof appAuthedAdminSettingsIndexRoute
  '/admin/members/$userId/$date': typeof appAuthedAdminMembersUserIdDateRoute
  '/admin/members/$userId': typeof appAuthedAdminMembersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_authed': typeof appAuthedRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/signup': typeof publicSignupRoute
  '/api/bootstrap-org': typeof ApiBootstrapOrgRoute
  '/api/me': typeof ApiMeRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/_authed/admin': typeof appAuthedAdminRouteRouteWithChildren
  '/(app)/_authed/dashboard': typeof appAuthedDashboardRoute
  '/(app)/_authed/profile': typeof appAuthedProfileRoute
  '/(public)/invite/$token': typeof publicInviteTokenRoute
  '/api/attendance/audits': typeof ApiAttendanceAuditsRoute
  '/api/attendance/break-end': typeof ApiAttendanceBreakEndRoute
  '/api/attendance/break-start': typeof ApiAttendanceBreakStartRoute
  '/api/attendance/clock-in': typeof ApiAttendanceClockInRoute
  '/api/attendance/clock-out': typeof ApiAttendanceClockOutRoute
  '/api/attendance/detail': typeof ApiAttendanceDetailRoute
  '/api/attendance/edit-entry': typeof ApiAttendanceEditEntryRoute
  '/api/attendance/list': typeof ApiAttendanceListRoute
  '/api/attendance/reminders': typeof ApiAttendanceRemindersRoute
  '/api/attendance/today': typeof ApiAttendanceTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/correction-requests/approve': typeof ApiCorrectionRequestsApproveRoute
  '/api/correction-requests/cancel': typeof ApiCorrectionRequestsCancelRoute
  '/api/correction-requests/create': typeof ApiCorrectionRequestsCreateRoute
  '/api/correction-requests/list-mine': typeof ApiCorrectionRequestsListMineRoute
  '/api/correction-requests/list-org': typeof ApiCorrectionRequestsListOrgRoute
  '/api/correction-requests/reject': typeof ApiCorrectionRequestsRejectRoute
  '/api/holidays/create': typeof ApiHolidaysCreateRoute
  '/api/holidays/delete': typeof ApiHolidaysDeleteRoute
  '/api/leave-requests/approve': typeof ApiLeaveRequestsApproveRoute
  '/api/leave-requests/cancel': typeof ApiLeaveRequestsCancelRoute
  '/api/leave-requests/create': typeof ApiLeaveRequestsCreateRoute
  '/api/leave-requests/list-mine': typeof ApiLeaveRequestsListMineRoute
  '/api/leave-requests/list-org': typeof ApiLeaveRequestsListOrgRoute
  '/api/leave-requests/reject': typeof ApiLeaveRequestsRejectRoute
  '/api/organization/accept-invitation': typeof ApiOrganizationAcceptInvitationRoute
  '/api/organization/change-role': typeof ApiOrganizationChangeRoleRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/members': typeof ApiOrganizationMembersRoute
  '/api/organization/remove-member': typeof ApiOrganizationRemoveMemberRoute
  '/api/organization/update': typeof ApiOrganizationUpdateRoute
  '/api/summary/csv': typeof ApiSummaryCsvRoute
  '/api/summary/lock': typeof ApiSummaryLockRoute
  '/api/summary/mine': typeof ApiSummaryMineRoute
  '/api/summary/monthly': typeof ApiSummaryMonthlyRoute
  '/api/holidays/': typeof ApiHolidaysIndexRoute
  '/(app)/_authed/admin/settings': typeof appAuthedAdminSettingsRouteRouteWithChildren
  '/(app)/_authed/admin/leaves': typeof appAuthedAdminLeavesRoute
  '/(app)/_authed/admin/requests': typeof appAuthedAdminRequestsRoute
  '/(app)/_authed/admin/summary': typeof appAuthedAdminSummaryRoute
  '/(app)/_authed/attendance/$date': typeof appAuthedAttendanceDateRoute
  '/(app)/_authed/leaves/new': typeof appAuthedLeavesNewRoute
  '/(app)/_authed/requests/new': typeof appAuthedRequestsNewRoute
  '/(app)/_authed/attendance/': typeof appAuthedAttendanceIndexRoute
  '/(app)/_authed/leaves/': typeof appAuthedLeavesIndexRoute
  '/(app)/_authed/requests/': typeof appAuthedRequestsIndexRoute
  '/(app)/_authed/admin/settings/holidays': typeof appAuthedAdminSettingsHolidaysRoute
  '/(app)/_authed/admin/settings/members': typeof appAuthedAdminSettingsMembersRoute
  '/(app)/_authed/admin/members/': typeof appAuthedAdminMembersIndexRoute
  '/(app)/_authed/admin/settings/': typeof appAuthedAdminSettingsIndexRoute
  '/(app)/_authed/admin/members/$userId/$date': typeof appAuthedAdminMembersUserIdDateRoute
  '/(app)/_authed/admin/members/$userId/': typeof appAuthedAdminMembersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/api/bootstrap-org'
    | '/api/me'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/invite/$token'
    | '/api/attendance/audits'
    | '/api/attendance/break-end'
    | '/api/attendance/break-start'
    | '/api/attendance/clock-in'
    | '/api/attendance/clock-out'
    | '/api/attendance/detail'
    | '/api/attendance/edit-entry'
    | '/api/attendance/list'
    | '/api/attendance/reminders'
    | '/api/attendance/today'
    | '/api/auth/$'
    | '/api/correction-requests/approve'
    | '/api/correction-requests/cancel'
    | '/api/correction-requests/create'
    | '/api/correction-requests/list-mine'
    | '/api/correction-requests/list-org'
    | '/api/correction-requests/reject'
    | '/api/holidays/create'
    | '/api/holidays/delete'
    | '/api/leave-requests/approve'
    | '/api/leave-requests/cancel'
    | '/api/leave-requests/create'
    | '/api/leave-requests/list-mine'
    | '/api/leave-requests/list-org'
    | '/api/leave-requests/reject'
    | '/api/organization/accept-invitation'
    | '/api/organization/change-role'
    | '/api/organization/invitations'
    | '/api/organization/members'
    | '/api/organization/remove-member'
    | '/api/organization/update'
    | '/api/summary/csv'
    | '/api/summary/lock'
    | '/api/summary/mine'
    | '/api/summary/monthly'
    | '/api/holidays/'
    | '/admin/settings'
    | '/admin/leaves'
    | '/admin/requests'
    | '/admin/summary'
    | '/attendance/$date'
    | '/leaves/new'
    | '/requests/new'
    | '/attendance/'
    | '/leaves/'
    | '/requests/'
    | '/admin/settings/holidays'
    | '/admin/settings/members'
    | '/admin/members/'
    | '/admin/settings/'
    | '/admin/members/$userId/$date'
    | '/admin/members/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/api/bootstrap-org'
    | '/api/me'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/invite/$token'
    | '/api/attendance/audits'
    | '/api/attendance/break-end'
    | '/api/attendance/break-start'
    | '/api/attendance/clock-in'
    | '/api/attendance/clock-out'
    | '/api/attendance/detail'
    | '/api/attendance/edit-entry'
    | '/api/attendance/list'
    | '/api/attendance/reminders'
    | '/api/attendance/today'
    | '/api/auth/$'
    | '/api/correction-requests/approve'
    | '/api/correction-requests/cancel'
    | '/api/correction-requests/create'
    | '/api/correction-requests/list-mine'
    | '/api/correction-requests/list-org'
    | '/api/correction-requests/reject'
    | '/api/holidays/create'
    | '/api/holidays/delete'
    | '/api/leave-requests/approve'
    | '/api/leave-requests/cancel'
    | '/api/leave-requests/create'
    | '/api/leave-requests/list-mine'
    | '/api/leave-requests/list-org'
    | '/api/leave-requests/reject'
    | '/api/organization/accept-invitation'
    | '/api/organization/change-role'
    | '/api/organization/invitations'
    | '/api/organization/members'
    | '/api/organization/remove-member'
    | '/api/organization/update'
    | '/api/summary/csv'
    | '/api/summary/lock'
    | '/api/summary/mine'
    | '/api/summary/monthly'
    | '/api/holidays'
    | '/admin/leaves'
    | '/admin/requests'
    | '/admin/summary'
    | '/attendance/$date'
    | '/leaves/new'
    | '/requests/new'
    | '/attendance'
    | '/leaves'
    | '/requests'
    | '/admin/settings/holidays'
    | '/admin/settings/members'
    | '/admin/members'
    | '/admin/settings'
    | '/admin/members/$userId/$date'
    | '/admin/members/$userId'
  id:
    | '__root__'
    | '/(app)/_authed'
    | '/(public)/login'
    | '/(public)/signup'
    | '/api/bootstrap-org'
    | '/api/me'
    | '/(public)/'
    | '/(app)/_authed/admin'
    | '/(app)/_authed/dashboard'
    | '/(app)/_authed/profile'
    | '/(public)/invite/$token'
    | '/api/attendance/audits'
    | '/api/attendance/break-end'
    | '/api/attendance/break-start'
    | '/api/attendance/clock-in'
    | '/api/attendance/clock-out'
    | '/api/attendance/detail'
    | '/api/attendance/edit-entry'
    | '/api/attendance/list'
    | '/api/attendance/reminders'
    | '/api/attendance/today'
    | '/api/auth/$'
    | '/api/correction-requests/approve'
    | '/api/correction-requests/cancel'
    | '/api/correction-requests/create'
    | '/api/correction-requests/list-mine'
    | '/api/correction-requests/list-org'
    | '/api/correction-requests/reject'
    | '/api/holidays/create'
    | '/api/holidays/delete'
    | '/api/leave-requests/approve'
    | '/api/leave-requests/cancel'
    | '/api/leave-requests/create'
    | '/api/leave-requests/list-mine'
    | '/api/leave-requests/list-org'
    | '/api/leave-requests/reject'
    | '/api/organization/accept-invitation'
    | '/api/organization/change-role'
    | '/api/organization/invitations'
    | '/api/organization/members'
    | '/api/organization/remove-member'
    | '/api/organization/update'
    | '/api/summary/csv'
    | '/api/summary/lock'
    | '/api/summary/mine'
    | '/api/summary/monthly'
    | '/api/holidays/'
    | '/(app)/_authed/admin/settings'
    | '/(app)/_authed/admin/leaves'
    | '/(app)/_authed/admin/requests'
    | '/(app)/_authed/admin/summary'
    | '/(app)/_authed/attendance/$date'
    | '/(app)/_authed/leaves/new'
    | '/(app)/_authed/requests/new'
    | '/(app)/_authed/attendance/'
    | '/(app)/_authed/leaves/'
    | '/(app)/_authed/requests/'
    | '/(app)/_authed/admin/settings/holidays'
    | '/(app)/_authed/admin/settings/members'
    | '/(app)/_authed/admin/members/'
    | '/(app)/_authed/admin/settings/'
    | '/(app)/_authed/admin/members/$userId/$date'
    | '/(app)/_authed/admin/members/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAuthedRouteRoute: typeof appAuthedRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicSignupRoute: typeof publicSignupRoute
  ApiBootstrapOrgRoute: typeof ApiBootstrapOrgRoute
  ApiMeRoute: typeof ApiMeRoute
  publicIndexRoute: typeof publicIndexRoute
  publicInviteTokenRoute: typeof publicInviteTokenRoute
  ApiAttendanceAuditsRoute: typeof ApiAttendanceAuditsRoute
  ApiAttendanceBreakEndRoute: typeof ApiAttendanceBreakEndRoute
  ApiAttendanceBreakStartRoute: typeof ApiAttendanceBreakStartRoute
  ApiAttendanceClockInRoute: typeof ApiAttendanceClockInRoute
  ApiAttendanceClockOutRoute: typeof ApiAttendanceClockOutRoute
  ApiAttendanceDetailRoute: typeof ApiAttendanceDetailRoute
  ApiAttendanceEditEntryRoute: typeof ApiAttendanceEditEntryRoute
  ApiAttendanceListRoute: typeof ApiAttendanceListRoute
  ApiAttendanceRemindersRoute: typeof ApiAttendanceRemindersRoute
  ApiAttendanceTodayRoute: typeof ApiAttendanceTodayRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCorrectionRequestsApproveRoute: typeof ApiCorrectionRequestsApproveRoute
  ApiCorrectionRequestsCancelRoute: typeof ApiCorrectionRequestsCancelRoute
  ApiCorrectionRequestsCreateRoute: typeof ApiCorrectionRequestsCreateRoute
  ApiCorrectionRequestsListMineRoute: typeof ApiCorrectionRequestsListMineRoute
  ApiCorrectionRequestsListOrgRoute: typeof ApiCorrectionRequestsListOrgRoute
  ApiCorrectionRequestsRejectRoute: typeof ApiCorrectionRequestsRejectRoute
  ApiHolidaysCreateRoute: typeof ApiHolidaysCreateRoute
  ApiHolidaysDeleteRoute: typeof ApiHolidaysDeleteRoute
  ApiLeaveRequestsApproveRoute: typeof ApiLeaveRequestsApproveRoute
  ApiLeaveRequestsCancelRoute: typeof ApiLeaveRequestsCancelRoute
  ApiLeaveRequestsCreateRoute: typeof ApiLeaveRequestsCreateRoute
  ApiLeaveRequestsListMineRoute: typeof ApiLeaveRequestsListMineRoute
  ApiLeaveRequestsListOrgRoute: typeof ApiLeaveRequestsListOrgRoute
  ApiLeaveRequestsRejectRoute: typeof ApiLeaveRequestsRejectRoute
  ApiOrganizationAcceptInvitationRoute: typeof ApiOrganizationAcceptInvitationRoute
  ApiOrganizationChangeRoleRoute: typeof ApiOrganizationChangeRoleRoute
  ApiOrganizationInvitationsRoute: typeof ApiOrganizationInvitationsRoute
  ApiOrganizationMembersRoute: typeof ApiOrganizationMembersRoute
  ApiOrganizationRemoveMemberRoute: typeof ApiOrganizationRemoveMemberRoute
  ApiOrganizationUpdateRoute: typeof ApiOrganizationUpdateRoute
  ApiSummaryCsvRoute: typeof ApiSummaryCsvRoute
  ApiSummaryLockRoute: typeof ApiSummaryLockRoute
  ApiSummaryMineRoute: typeof ApiSummaryMineRoute
  ApiSummaryMonthlyRoute: typeof ApiSummaryMonthlyRoute
  ApiHolidaysIndexRoute: typeof ApiHolidaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-org': {
      id: '/api/bootstrap-org'
      path: '/api/bootstrap-org'
      fullPath: '/api/bootstrap-org'
      preLoaderRoute: typeof ApiBootstrapOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed': {
      id: '/(app)/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holidays/': {
      id: '/api/holidays/'
      path: '/api/holidays'
      fullPath: '/api/holidays/'
      preLoaderRoute: typeof ApiHolidaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/monthly': {
      id: '/api/summary/monthly'
      path: '/api/summary/monthly'
      fullPath: '/api/summary/monthly'
      preLoaderRoute: typeof ApiSummaryMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/mine': {
      id: '/api/summary/mine'
      path: '/api/summary/mine'
      fullPath: '/api/summary/mine'
      preLoaderRoute: typeof ApiSummaryMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/lock': {
      id: '/api/summary/lock'
      path: '/api/summary/lock'
      fullPath: '/api/summary/lock'
      preLoaderRoute: typeof ApiSummaryLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/csv': {
      id: '/api/summary/csv'
      path: '/api/summary/csv'
      fullPath: '/api/summary/csv'
      preLoaderRoute: typeof ApiSummaryCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/update': {
      id: '/api/organization/update'
      path: '/api/organization/update'
      fullPath: '/api/organization/update'
      preLoaderRoute: typeof ApiOrganizationUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/remove-member': {
      id: '/api/organization/remove-member'
      path: '/api/organization/remove-member'
      fullPath: '/api/organization/remove-member'
      preLoaderRoute: typeof ApiOrganizationRemoveMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/members': {
      id: '/api/organization/members'
      path: '/api/organization/members'
      fullPath: '/api/organization/members'
      preLoaderRoute: typeof ApiOrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/invitations': {
      id: '/api/organization/invitations'
      path: '/api/organization/invitations'
      fullPath: '/api/organization/invitations'
      preLoaderRoute: typeof ApiOrganizationInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/change-role': {
      id: '/api/organization/change-role'
      path: '/api/organization/change-role'
      fullPath: '/api/organization/change-role'
      preLoaderRoute: typeof ApiOrganizationChangeRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/accept-invitation': {
      id: '/api/organization/accept-invitation'
      path: '/api/organization/accept-invitation'
      fullPath: '/api/organization/accept-invitation'
      preLoaderRoute: typeof ApiOrganizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/reject': {
      id: '/api/leave-requests/reject'
      path: '/api/leave-requests/reject'
      fullPath: '/api/leave-requests/reject'
      preLoaderRoute: typeof ApiLeaveRequestsRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/list-org': {
      id: '/api/leave-requests/list-org'
      path: '/api/leave-requests/list-org'
      fullPath: '/api/leave-requests/list-org'
      preLoaderRoute: typeof ApiLeaveRequestsListOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/list-mine': {
      id: '/api/leave-requests/list-mine'
      path: '/api/leave-requests/list-mine'
      fullPath: '/api/leave-requests/list-mine'
      preLoaderRoute: typeof ApiLeaveRequestsListMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/create': {
      id: '/api/leave-requests/create'
      path: '/api/leave-requests/create'
      fullPath: '/api/leave-requests/create'
      preLoaderRoute: typeof ApiLeaveRequestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/cancel': {
      id: '/api/leave-requests/cancel'
      path: '/api/leave-requests/cancel'
      fullPath: '/api/leave-requests/cancel'
      preLoaderRoute: typeof ApiLeaveRequestsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave-requests/approve': {
      id: '/api/leave-requests/approve'
      path: '/api/leave-requests/approve'
      fullPath: '/api/leave-requests/approve'
      preLoaderRoute: typeof ApiLeaveRequestsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holidays/delete': {
      id: '/api/holidays/delete'
      path: '/api/holidays/delete'
      fullPath: '/api/holidays/delete'
      preLoaderRoute: typeof ApiHolidaysDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holidays/create': {
      id: '/api/holidays/create'
      path: '/api/holidays/create'
      fullPath: '/api/holidays/create'
      preLoaderRoute: typeof ApiHolidaysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/reject': {
      id: '/api/correction-requests/reject'
      path: '/api/correction-requests/reject'
      fullPath: '/api/correction-requests/reject'
      preLoaderRoute: typeof ApiCorrectionRequestsRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/list-org': {
      id: '/api/correction-requests/list-org'
      path: '/api/correction-requests/list-org'
      fullPath: '/api/correction-requests/list-org'
      preLoaderRoute: typeof ApiCorrectionRequestsListOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/list-mine': {
      id: '/api/correction-requests/list-mine'
      path: '/api/correction-requests/list-mine'
      fullPath: '/api/correction-requests/list-mine'
      preLoaderRoute: typeof ApiCorrectionRequestsListMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/create': {
      id: '/api/correction-requests/create'
      path: '/api/correction-requests/create'
      fullPath: '/api/correction-requests/create'
      preLoaderRoute: typeof ApiCorrectionRequestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/cancel': {
      id: '/api/correction-requests/cancel'
      path: '/api/correction-requests/cancel'
      fullPath: '/api/correction-requests/cancel'
      preLoaderRoute: typeof ApiCorrectionRequestsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correction-requests/approve': {
      id: '/api/correction-requests/approve'
      path: '/api/correction-requests/approve'
      fullPath: '/api/correction-requests/approve'
      preLoaderRoute: typeof ApiCorrectionRequestsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/today': {
      id: '/api/attendance/today'
      path: '/api/attendance/today'
      fullPath: '/api/attendance/today'
      preLoaderRoute: typeof ApiAttendanceTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/reminders': {
      id: '/api/attendance/reminders'
      path: '/api/attendance/reminders'
      fullPath: '/api/attendance/reminders'
      preLoaderRoute: typeof ApiAttendanceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/list': {
      id: '/api/attendance/list'
      path: '/api/attendance/list'
      fullPath: '/api/attendance/list'
      preLoaderRoute: typeof ApiAttendanceListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/edit-entry': {
      id: '/api/attendance/edit-entry'
      path: '/api/attendance/edit-entry'
      fullPath: '/api/attendance/edit-entry'
      preLoaderRoute: typeof ApiAttendanceEditEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/detail': {
      id: '/api/attendance/detail'
      path: '/api/attendance/detail'
      fullPath: '/api/attendance/detail'
      preLoaderRoute: typeof ApiAttendanceDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/clock-out': {
      id: '/api/attendance/clock-out'
      path: '/api/attendance/clock-out'
      fullPath: '/api/attendance/clock-out'
      preLoaderRoute: typeof ApiAttendanceClockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/clock-in': {
      id: '/api/attendance/clock-in'
      path: '/api/attendance/clock-in'
      fullPath: '/api/attendance/clock-in'
      preLoaderRoute: typeof ApiAttendanceClockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/break-start': {
      id: '/api/attendance/break-start'
      path: '/api/attendance/break-start'
      fullPath: '/api/attendance/break-start'
      preLoaderRoute: typeof ApiAttendanceBreakStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/break-end': {
      id: '/api/attendance/break-end'
      path: '/api/attendance/break-end'
      fullPath: '/api/attendance/break-end'
      preLoaderRoute: typeof ApiAttendanceBreakEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/audits': {
      id: '/api/attendance/audits'
      path: '/api/attendance/audits'
      fullPath: '/api/attendance/audits'
      preLoaderRoute: typeof ApiAttendanceAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/invite/$token': {
      id: '/(public)/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof publicInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed/profile': {
      id: '/(app)/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appAuthedProfileRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/dashboard': {
      id: '/(app)/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAuthedDashboardRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/admin': {
      id: '/(app)/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAuthedAdminRouteRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/requests/': {
      id: '/(app)/_authed/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof appAuthedRequestsIndexRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/leaves/': {
      id: '/(app)/_authed/leaves/'
      path: '/leaves'
      fullPath: '/leaves/'
      preLoaderRoute: typeof appAuthedLeavesIndexRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/attendance/': {
      id: '/(app)/_authed/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof appAuthedAttendanceIndexRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/requests/new': {
      id: '/(app)/_authed/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof appAuthedRequestsNewRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/leaves/new': {
      id: '/(app)/_authed/leaves/new'
      path: '/leaves/new'
      fullPath: '/leaves/new'
      preLoaderRoute: typeof appAuthedLeavesNewRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/attendance/$date': {
      id: '/(app)/_authed/attendance/$date'
      path: '/attendance/$date'
      fullPath: '/attendance/$date'
      preLoaderRoute: typeof appAuthedAttendanceDateRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/admin/summary': {
      id: '/(app)/_authed/admin/summary'
      path: '/summary'
      fullPath: '/admin/summary'
      preLoaderRoute: typeof appAuthedAdminSummaryRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/requests': {
      id: '/(app)/_authed/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof appAuthedAdminRequestsRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/leaves': {
      id: '/(app)/_authed/admin/leaves'
      path: '/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof appAuthedAdminLeavesRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/settings': {
      id: '/(app)/_authed/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof appAuthedAdminSettingsRouteRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/settings/': {
      id: '/(app)/_authed/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof appAuthedAdminSettingsIndexRouteImport
      parentRoute: typeof appAuthedAdminSettingsRouteRoute
    }
    '/(app)/_authed/admin/members/': {
      id: '/(app)/_authed/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof appAuthedAdminMembersIndexRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/settings/members': {
      id: '/(app)/_authed/admin/settings/members'
      path: '/members'
      fullPath: '/admin/settings/members'
      preLoaderRoute: typeof appAuthedAdminSettingsMembersRouteImport
      parentRoute: typeof appAuthedAdminSettingsRouteRoute
    }
    '/(app)/_authed/admin/settings/holidays': {
      id: '/(app)/_authed/admin/settings/holidays'
      path: '/holidays'
      fullPath: '/admin/settings/holidays'
      preLoaderRoute: typeof appAuthedAdminSettingsHolidaysRouteImport
      parentRoute: typeof appAuthedAdminSettingsRouteRoute
    }
    '/(app)/_authed/admin/members/$userId/': {
      id: '/(app)/_authed/admin/members/$userId/'
      path: '/members/$userId'
      fullPath: '/admin/members/$userId/'
      preLoaderRoute: typeof appAuthedAdminMembersUserIdIndexRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
    '/(app)/_authed/admin/members/$userId/$date': {
      id: '/(app)/_authed/admin/members/$userId/$date'
      path: '/members/$userId/$date'
      fullPath: '/admin/members/$userId/$date'
      preLoaderRoute: typeof appAuthedAdminMembersUserIdDateRouteImport
      parentRoute: typeof appAuthedAdminRouteRoute
    }
  }
}

interface appAuthedAdminSettingsRouteRouteChildren {
  appAuthedAdminSettingsHolidaysRoute: typeof appAuthedAdminSettingsHolidaysRoute
  appAuthedAdminSettingsMembersRoute: typeof appAuthedAdminSettingsMembersRoute
  appAuthedAdminSettingsIndexRoute: typeof appAuthedAdminSettingsIndexRoute
}

const appAuthedAdminSettingsRouteRouteChildren: appAuthedAdminSettingsRouteRouteChildren =
  {
    appAuthedAdminSettingsHolidaysRoute: appAuthedAdminSettingsHolidaysRoute,
    appAuthedAdminSettingsMembersRoute: appAuthedAdminSettingsMembersRoute,
    appAuthedAdminSettingsIndexRoute: appAuthedAdminSettingsIndexRoute,
  }

const appAuthedAdminSettingsRouteRouteWithChildren =
  appAuthedAdminSettingsRouteRoute._addFileChildren(
    appAuthedAdminSettingsRouteRouteChildren,
  )

interface appAuthedAdminRouteRouteChildren {
  appAuthedAdminSettingsRouteRoute: typeof appAuthedAdminSettingsRouteRouteWithChildren
  appAuthedAdminLeavesRoute: typeof appAuthedAdminLeavesRoute
  appAuthedAdminRequestsRoute: typeof appAuthedAdminRequestsRoute
  appAuthedAdminSummaryRoute: typeof appAuthedAdminSummaryRoute
  appAuthedAdminMembersIndexRoute: typeof appAuthedAdminMembersIndexRoute
  appAuthedAdminMembersUserIdDateRoute: typeof appAuthedAdminMembersUserIdDateRoute
  appAuthedAdminMembersUserIdIndexRoute: typeof appAuthedAdminMembersUserIdIndexRoute
}

const appAuthedAdminRouteRouteChildren: appAuthedAdminRouteRouteChildren = {
  appAuthedAdminSettingsRouteRoute:
    appAuthedAdminSettingsRouteRouteWithChildren,
  appAuthedAdminLeavesRoute: appAuthedAdminLeavesRoute,
  appAuthedAdminRequestsRoute: appAuthedAdminRequestsRoute,
  appAuthedAdminSummaryRoute: appAuthedAdminSummaryRoute,
  appAuthedAdminMembersIndexRoute: appAuthedAdminMembersIndexRoute,
  appAuthedAdminMembersUserIdDateRoute: appAuthedAdminMembersUserIdDateRoute,
  appAuthedAdminMembersUserIdIndexRoute: appAuthedAdminMembersUserIdIndexRoute,
}

const appAuthedAdminRouteRouteWithChildren =
  appAuthedAdminRouteRoute._addFileChildren(appAuthedAdminRouteRouteChildren)

interface appAuthedRouteRouteChildren {
  appAuthedAdminRouteRoute: typeof appAuthedAdminRouteRouteWithChildren
  appAuthedDashboardRoute: typeof appAuthedDashboardRoute
  appAuthedProfileRoute: typeof appAuthedProfileRoute
  appAuthedAttendanceDateRoute: typeof appAuthedAttendanceDateRoute
  appAuthedLeavesNewRoute: typeof appAuthedLeavesNewRoute
  appAuthedRequestsNewRoute: typeof appAuthedRequestsNewRoute
  appAuthedAttendanceIndexRoute: typeof appAuthedAttendanceIndexRoute
  appAuthedLeavesIndexRoute: typeof appAuthedLeavesIndexRoute
  appAuthedRequestsIndexRoute: typeof appAuthedRequestsIndexRoute
}

const appAuthedRouteRouteChildren: appAuthedRouteRouteChildren = {
  appAuthedAdminRouteRoute: appAuthedAdminRouteRouteWithChildren,
  appAuthedDashboardRoute: appAuthedDashboardRoute,
  appAuthedProfileRoute: appAuthedProfileRoute,
  appAuthedAttendanceDateRoute: appAuthedAttendanceDateRoute,
  appAuthedLeavesNewRoute: appAuthedLeavesNewRoute,
  appAuthedRequestsNewRoute: appAuthedRequestsNewRoute,
  appAuthedAttendanceIndexRoute: appAuthedAttendanceIndexRoute,
  appAuthedLeavesIndexRoute: appAuthedLeavesIndexRoute,
  appAuthedRequestsIndexRoute: appAuthedRequestsIndexRoute,
}

const appAuthedRouteRouteWithChildren = appAuthedRouteRoute._addFileChildren(
  appAuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appAuthedRouteRoute: appAuthedRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicSignupRoute: publicSignupRoute,
  ApiBootstrapOrgRoute: ApiBootstrapOrgRoute,
  ApiMeRoute: ApiMeRoute,
  publicIndexRoute: publicIndexRoute,
  publicInviteTokenRoute: publicInviteTokenRoute,
  ApiAttendanceAuditsRoute: ApiAttendanceAuditsRoute,
  ApiAttendanceBreakEndRoute: ApiAttendanceBreakEndRoute,
  ApiAttendanceBreakStartRoute: ApiAttendanceBreakStartRoute,
  ApiAttendanceClockInRoute: ApiAttendanceClockInRoute,
  ApiAttendanceClockOutRoute: ApiAttendanceClockOutRoute,
  ApiAttendanceDetailRoute: ApiAttendanceDetailRoute,
  ApiAttendanceEditEntryRoute: ApiAttendanceEditEntryRoute,
  ApiAttendanceListRoute: ApiAttendanceListRoute,
  ApiAttendanceRemindersRoute: ApiAttendanceRemindersRoute,
  ApiAttendanceTodayRoute: ApiAttendanceTodayRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCorrectionRequestsApproveRoute: ApiCorrectionRequestsApproveRoute,
  ApiCorrectionRequestsCancelRoute: ApiCorrectionRequestsCancelRoute,
  ApiCorrectionRequestsCreateRoute: ApiCorrectionRequestsCreateRoute,
  ApiCorrectionRequestsListMineRoute: ApiCorrectionRequestsListMineRoute,
  ApiCorrectionRequestsListOrgRoute: ApiCorrectionRequestsListOrgRoute,
  ApiCorrectionRequestsRejectRoute: ApiCorrectionRequestsRejectRoute,
  ApiHolidaysCreateRoute: ApiHolidaysCreateRoute,
  ApiHolidaysDeleteRoute: ApiHolidaysDeleteRoute,
  ApiLeaveRequestsApproveRoute: ApiLeaveRequestsApproveRoute,
  ApiLeaveRequestsCancelRoute: ApiLeaveRequestsCancelRoute,
  ApiLeaveRequestsCreateRoute: ApiLeaveRequestsCreateRoute,
  ApiLeaveRequestsListMineRoute: ApiLeaveRequestsListMineRoute,
  ApiLeaveRequestsListOrgRoute: ApiLeaveRequestsListOrgRoute,
  ApiLeaveRequestsRejectRoute: ApiLeaveRequestsRejectRoute,
  ApiOrganizationAcceptInvitationRoute: ApiOrganizationAcceptInvitationRoute,
  ApiOrganizationChangeRoleRoute: ApiOrganizationChangeRoleRoute,
  ApiOrganizationInvitationsRoute: ApiOrganizationInvitationsRoute,
  ApiOrganizationMembersRoute: ApiOrganizationMembersRoute,
  ApiOrganizationRemoveMemberRoute: ApiOrganizationRemoveMemberRoute,
  ApiOrganizationUpdateRoute: ApiOrganizationUpdateRoute,
  ApiSummaryCsvRoute: ApiSummaryCsvRoute,
  ApiSummaryLockRoute: ApiSummaryLockRoute,
  ApiSummaryMineRoute: ApiSummaryMineRoute,
  ApiSummaryMonthlyRoute: ApiSummaryMonthlyRoute,
  ApiHolidaysIndexRoute: ApiHolidaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
